DROP TABLE `executives`;

CREATE TABLE `executives` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `portfolio` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `contact` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

INSERT INTO `executives` (`title`, `full_name`, `portfolio`, `email`, `contact`) VALUES
('Mr', 'Babajide Sanwo-Olu', 'Governor', 'bosgov@lagosstate.gov.ng', '2349017077777'),
('Dr', 'Kadri Obafemi-Hamzat', 'Deputy Governor', 'kohdg@lagosstate.gov.ng', '2348032215026'),
('Mrs', 'Sherifat Folashade Jaji','Secretary to the State Government', 'sjaji@lagosstate.gov.ng', '2348023122483'),
('Mr', 'Hakeem Muri-Okunola', 'Head of Service', 'hmo@lagosstate.gov.ng', '2348034030236'),
('Mr', 'Tayo Akinmade Ayinde', 'Chief of Staff', 'tayoayinde@yahoo.co.uk', '2348022903706'),
('Mr', 'Gboyega Soyannwo', 'Deputy Chief of Staff', 'gsoyannwo@lagosstate.gov.ng', '2348033084128'),
('Mr', 'Rabiu Onaolapo Olowo', 'Commissioner for Finance', 'rabiuolowo@lagosstate.gov.ng', '2348022903706'),
('Mrs', 'Folashade Adefisayo', 'Commissioner for Education', 'fadefisayoo@lagosstate.gov.ng', '2348033008550'),
('Professor', 'Akin Abayomi', 'Commissioner for Health', 'akinabayomi@lagosstate.gov.ng', '2349031101982'),
('Dr', 'Idris Salako-Olu', 'Commissioner for Physical Planning and Urban Development', 'isalako@lagosstate.gov.ng', '2348053500032'),
('Mr', 'Tunji Bello', 'Commissioner for The Environment and Water Resources', 'tbello@lagosstate.gov.ng', '2348035272200'),
('Mr', 'Gbenga Omotoso', 'Commissioner for Information and Strategy', 'gomotoso@lagosstate.gov.ng', '2348034004237'),
('Mrs', 'Bolaji Dada', 'Commissioner for Women Affairs and Poverty Alleviation', 'bolajidada@lagosstate.gov.ng', '2348033244981'),
('Mr', 'Lere Odusote', 'Commissioner for Energy and Natural Resources', 'lodusote@lagosstate.gov.ng', '2348175016555'),
('Dr', 'Federic Oladeinde', 'Commissioner for Transportation', 'foladeinde@lagosstate.gov.ng', '2348068519606'),
('Mr', 'Gbolahan Lawal', 'Commissioner for Agriculture', 'glawal@lagosstate.gov.ng', '2348055552407'),
('', 'Moruf Akideru Fatai', 'Commissioner for Housing', 'mfatai@lagosstate.gov.ng', '2348099000555'),
('Mr', 'Moyo Onigbanjo (SAN)', 'Attorney General and Commissioner for Justice', 'm.onigbanjo@lagosstate.gov.ng', '2348033243869'),
('Mr', 'Hakeen Fahm', 'Commissioner for Science and Technology', 'hakeemfahm@lagosstate.gov.ng', '2348183374053'),
('Mrs', 'Ajibola Ponnle', 'Commissioner for Establishments, Training and Pensions', 'aponle@lagosstate.gov.ng', '2348023143545'),
('Mr', 'Segun Dawodu', 'Commissioner for Youth and Social Development', 'segundawodu@lagosstate.gov.ng', '2348022241430'),
('', 'Anofi Olanrewaju Elegushi', 'Commissioner for Home Affairs', 'aelegushi@lagosstate.gov.ng', '2347055555886'),
('Mr', 'Wale Ahmed', 'Commissioner for Local Government and Community Affairs', 'wahmed@lagosstate.gov.ng', '2348022234870'),
('Mrs', 'Lola Akande', 'Commissioner for Commerce and Industry', 'lolaakande@lagosstate.gov.ng', '2348028610411'),
('Mrs', 'Uzamat Akinbile-Yusuf', 'Commissioner for Tourism, Arts and Culture', 'uakinbile-yusuf@lagosstate.gov.ng', '2348033267731'),
('Mr', 'Sam Egube', 'Commissioner for Economic Planning and Budget', 'segube@lagosstate.gov.ng', '2348029990194'),
('Engineer', 'Tayo Bamgbose-Martins', 'Commissioner for Special Duties and Inter-governmental Relations', '', ''),
('Architect', 'Kabiru Ahmed Abdullahi', 'Commissioner for Waterfront Infrastructure', 'k.abdullahi@lagosstate.gov.ng', '2348067770777'),
('Mrs', 'Yetunde Arobieke', 'Commissioner for Wealth Creation and Employment', 'yarobieke@lagosstate.gov.ng', '2348033006419'),
('Engineer', 'Aramide Adeyoye', 'Special Adviser Works and Infrastructure', 'aadeyoye@lagosstate.gov.ng', '2348077761036'),
('Ms', 'Ruth Bisola Olusanya', 'Special Adviser for Agriculture', 'rbolusanya@lagosstate.gov.ng', '2348069359523'),
('Princess', 'Aderemi Adebowale', 'Special Adviser, Office of  Civic Engagement', 'remiadebowale@lagosstate.gov.ng', '234815558770'),
('Mr', 'Afolabi Ayantayo', 'Special Adviser on Political and Legislative Affairs', 'aayantayo@lagosstate.gov.ng', '2348054539126'),
('Mrs', 'Toke Benson-Awoyinka', 'Special Adviser for Housing', 'tbenson-awoyinka@lagosstate.gov.ng', '234808155288'),
('Mr', 'Joe Igbokwe', 'Special Adviser Office of Drainage Services', 'jigbokwe@lagosstate.gov.ng', '2348033060452'),
('Mr', 'Tunbosun Alake', 'Special Adviser for Innovation and Technology', 'talake@lagosstate.gov.ng', '2348180445694'),
('Honourable', 'Ayuba Ganiu Adele', 'Special Adviser for Urban Development', '', ''),
('Mr', 'Oyerinde Olugbenga Olanrewaju', 'Special Adviser for Central Business District', '', ''),
('', 'Bonu Solomon Saanu', 'Special Adviser for Arts and Culture', 'bsaanu@lagosstate.gov.ng', '2348032661223'),
('Mr', 'Oluwatoyin Fayinka', 'Special Adviser for Transportation', 'ofayinka@lagosstate.gov.ng', '2348023059317'),
('', 'Oladele Ajayi', 'Special Adviser for Commerce and Industry', 'deleajayi@lagosstate.gov.ng', '2348023290562'),
('Mr', 'Tokunbo Wahab', 'Special Adviser for Education', 'twahab@lagosstate.gov.ng', '2348022042478');